### ISSUE TITLE
LPAPR netboot Error

### ISSUE THREAD

**Issue by itester394** [ocp-power-automation/ocp4-upi-powervm-hmc#1]
I've installed everything as per the steps but when I run the playbook:

 ansible-playbook  -e @vars-powervm.yaml playbooks/main.yaml

it keeps runing till it reach this stage:

+++++++++++++++++++++++
TASK [bootup-nodes : netboot bootstrap node] *********************************************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "orig_mac=02:DE:E7:68:23:02\npvm_mac=`echo ${orig_mac//:}`\npvmcec=S922a\npvmlpar=ocp4-bootstrap\npvm_profile=`ssh -o StrictHostKeyChecking=no hscroot@xxx.xxx.xxx.xxx. \"lssyscfg -r lpar -m ${pvmcec} --filter lpar_names=${pvmlpar} -F curr_profile\"`\nremote_cmd=\"lpar_netboot -f -t ent -m ${pvm_mac} -s auto -d auto ${pvmlpar} ${pvm_profile} ${pvmcec}\"\nssh -o StrictHostKeyChecking=no hscroot@xxx.xxx.xxx.xxx. \"${remote_cmd}\"\n", "delta": "0:02:17.963866", "end": "2021-02-26 09:08:29.950819", "msg": "non-zero return code", "rc": 1, "start": "2021-02-26 09:06:11.986953", "stderr": "lpar_netboot: Error : Close command sent/bin/stty: standard input: Inappropriate ioctl for device\nlpar_netboot: The network boot ended in an error.", "stderr_lines": ["lpar_netboot: Error : Close command sent/bin/stty: standard input: Inappropriate ioctl for device", "lpar_netboot: The network boot ended in an error."], "stdout": "# Connecting to ocp4-bootstrap\n# Connected\n# Checking for power off.\n# Power off the node\n# Wait for power off.\n# Power off complete.\n# Power on ocp4-bootstrap to Open Firmware.\n# Power on complete.\n# Getting adapter location codes.\nBOOTP initiated!\n# bootp sent over network.\n Parameters: \r\n----------------  \r\nchosen-network-type = ethernet,auto,none,auto\r\nserver IP           = 0.0.0.0\r\nclient IP           = 0.0.0.0\r\ngateway IP          = 0.0.0.0\r\ndevice              = /vdevice/l-lan@30000002\r\nMAC address         = 02 de e7 68 23 02 \r\nloc-code            = U9009.22A.zzzzzzz-V20-C2-T1\r\n\r\nBOOTP request retry attempt: 1 \r\nBOOTP request retry attempt: 2 \r\nBOOTP request retry attempt: 3 \r\nBOOTP request retry attempt: 4 \r\n\t!BA01B015", "stdout_lines": ["# Connecting to ocp4-bootstrap", "# Connected", "# Checking for power off.", "# Power off the node", "# Wait for power off.", "# Power off complete.", "# Power on ocp4-bootstrap to Open Firmware.", "# Power on complete.", "# Getting adapter location codes.", "BOOTP initiated!", "# bootp sent over network.", " Parameters: ", "----------------  ", "chosen-network-type = ethernet,auto,none,auto", "server IP           = 0.0.0.0", "client IP           = 0.0.0.0", "gateway IP          = 0.0.0.0", "device              = /vdevice/l-lan@30000002", "MAC address         = 02 de e7 68 23 02 ", "loc-code            = U9009.22A.zzzzzz-V20-C2-T1", "", "BOOTP request retry attempt: 1 ", "BOOTP request retry attempt: 2 ", "BOOTP request retry attempt: 3 ", "BOOTP request retry attempt: 4 ", "\t!BA01B015"]}

+++++++++++++++++++++++++++

I use static ips!

Thanks

**Comment by itester394** [comment]
I use static ips!

**Comment by dannert** [comment]
Try replacing in the "inventory" file on Bastion/Helper node in the cloned Git repository the "localhost" with the IP of Bastion/Helper node. That worked in my case.

**Comment by cs-zhang** [comment]
Update `inventory` to use bastion's IP to replace the `localhost` can fix this problem.
