### ISSUE TITLE
update_ignition_bootstrap.py is missing filesystem stanza for chrony.conf entry

### ISSUE THREAD

**Issue by dannert** [ocp-power-automation/ocp4-upi-powervm-hmc#2]
Issue is with: ocp4-playbooks/playbooks/roles/ocp-config/files/update_ignition_bootstrap.py
The script fails to write the "filesystem" stanze for the chrony.conf file.
Correct content needs to look like this:
...
if os.path.isfile('/tmp/chrony.conf.tmp'):
    with open("/tmp/chrony.conf.tmp", "rb") as chronyconf:
        chrony_b64 = base64.standard_b64encode(chronyconf.read()).decode().strip()
        files.append(
        {
            'filesystem': 'root',
            'path': '/etc/chrony.conf',
            'user': {
                'name': 'root'
            },
            'mode': 420,
            'contents': {
                'source': 'data:text/plain;charset=utf-8;base64,' + chrony_b64,
                'verification': {}
                },
            'overwrite': True
        })
....
Note the added line:
            'filesystem': 'root',

With that change I was able to successfully install OCP 4.5 with the provided playbooks.

**Comment by cs-zhang** [comment]
This issue should be opened against https://github.com/ocp-power-automation/ocp4-playbooks. I'll create the issue there and fix it.
